apiVersion: v1
kind: Service
metadata:
  name: dev-go-app
  labels:
    app: dev-go-app
spec:
  type: ClusterIP
  selector:
    app: dev-go-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
